export const seedData = {
  binLocations: [
    { name: "warehouse", nombre: "bodega" },
    { name: "zone", nombre: "zona" },
    { name: "aisle", nombre: "pasillo" },
    { name: "rack", nombre: "estante" },
    { name: "shelf", nombre: "fila del estante" },
    { name: "bin", nombre: "estante" },
  ],
  carriers: [
    { name: "Interna" },
    { name: "Mercadolibre" },
    { name: "Noventa9Minutos" },
    { name: "Fedex" },
    { name: "Paquetexpress" },
    { name: "Tres Guerras" },
    { name: "Estafeta" },
    { name: "Enviacom - fedex" },
    { name: "Enviacom - paquetexpress" },
    { name: "Enviacom - noventa9Minutos" },
    { name: "Enviacom - estafeta" },
  ],
  categories: [
    { name: "Accesorios para vehículos" },
    { name: "Agro" },
    { name: "Alimentos y Bebidas" },
    { name: "Animales y Mascotas" },
    { name: "Antigüedades y Colecciones" },
    { name: "Arte, Papelería y Mercería" },
  ],
  paymentMethods: [
    { name: "Efectivo" },
    { name: "Transferencia" },
    { name: "Tarjeta de crédito" },
    { name: "Tarjeta de débito" },
    { name: "Pagos diferidos" },
  ],
  salesFunnel: [
    { name: "Mercadolibre" },
    { name: "Shopify" },
    { name: "Facebook" },
    { name: "Instagram" },
    { name: "Marketplace Facebook" },
    { name: "Marketplace Instagram" },
    { name: "Venta directa" },
  ],
};
